# Generated by Django 5.1.7 on 2025-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementform',
            name='current_process',
            field=models.CharField(choices=[('manual', 'Fully Manual'), ('partial', 'Partially Digital'), ('digital', 'Fully Digital')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='requirementform',
            name='digital_software',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
