# Generated by Django 5.1.7 on 2025-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0002_requirementform_current_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementform',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
