# Generated by Django 5.1.7 on 2025-04-09 11:26

import requirements_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0003_requirementform_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementform',
            name='flowchart',
            field=models.FileField(null=True, upload_to=requirements_app.models.RequirementForm.get_flowchart_upload_path),
        ),
    ]
