# Generated by Django 5.1.7 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0004_requirementform_flowchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementform',
            name='digital_limitation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requirementform',
            name='manual_limitation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
