# Generated by Django 5.1.7 on 2025-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0005_requirementform_digital_limitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementform',
            name='digital_limitation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='manual_limitation',
            field=models.TextField(blank=True),
        ),
    ]
