# Generated by Django 5.1.7 on 2025-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0007_remove_requirementform_current_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementform',
            name='ease_of_access',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='error_possibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='expected_analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='expected_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='expected_reports',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='external_connectivity_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='internal_connectivity_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='people_involved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='process_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='process_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='process_steps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
