# Generated by Django 5.1.7 on 2025-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0009_alter_requirementform_external_connectivity_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementform',
            name='ease_of_access',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='error_possibility',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='people_involved',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='process_steps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requirementform',
            name='time_taken',
            field=models.PositiveIntegerField(),
        ),
    ]
