# Generated by Django 5.1.7 on 2025-04-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0010_alter_requirementform_ease_of_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementform',
            name='ease_of_access',
        ),
        migrations.RemoveField(
            model_name='requirementform',
            name='error_possibility',
        ),
    ]
