# Generated by Django 5.1.7 on 2025-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0011_remove_requirementform_ease_of_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementform',
            name='process_steps_detail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
